const ADMIN_LOCAL_KEY="eduvulcan_teacher_changes";
let adminLessons=[];
let adminChanges=[];
const $=id=>document.getElementById(id);
const isoDate=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`;};
const esc=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function localChanges(){try{return JSON.parse(localStorage.getItem(ADMIN_LOCAL_KEY)||"[]");}catch(e){return [];}}
function saveLocal(){localStorage.setItem(ADMIN_LOCAL_KEY,JSON.stringify(adminChanges));}
function notice(text,error=false){$("admin-notice").textContent=text;$("admin-notice").classList.toggle("show",!!text);$("admin-notice").style.background=error?"#fff1ef":"";$("admin-notice").style.color=error?"#8d2b26":"";}
function nextSchoolDay(){const d=new Date();d.setHours(0,0,0,0);if(d.getDay()===0)d.setDate(d.getDate()+1);if(d.getDay()===6)d.setDate(d.getDate()+2);return isoDate(d);}
function lessonsForDate(value){const d=new Date(`${value}T00:00:00`), weekday=d.getDay()-1;return adminLessons.filter(x=>Number(x.weekday)===weekday).sort((a,b)=>Number(a.lesson_number)-Number(b.lesson_number));}
function fillLessons(){const value=$("change-date").value;const lessons=lessonsForDate(value);$("change-lesson").innerHTML=(lessons.length?lessons:Array.from({length:8},(_,i)=>({lesson_number:i+1,start_time:"",end_time:"",subject:`Lekcja ${i+1}`,room:""}))).map(x=>`<option value="${esc(x.id||"")}" data-number="${x.lesson_number}" data-subject="${esc(x.subject||"")}" data-room="${esc(x.room||"")}">${x.lesson_number}. ${esc(x.subject||"Lekcja")}${x.start_time?` · ${esc(String(x.start_time).slice(0,5))}`:""}</option>`).join("");}
function renderChanges(){const date=$("list-date").value;const list=adminChanges.filter(x=>!date||x.lesson_date===date).sort((a,b)=>String(a.lesson_date).localeCompare(String(b.lesson_date)));$("changes-list").innerHTML=list.length?list.map(x=>`<article class="change-item"><div class="change-meta"><span>${esc(x.lesson_date)} · lekcja ${esc(x.lesson_number)}</span><span>${x.change_type==="block"?"Blok":x.change_type==="cancelled"?"Odwołana":"Zastępstwo"}</span></div><strong>${esc(x.replacement_subject||"Zmiana lekcji")}</strong><div>${esc(x.replacement_teacher||"Bez przypisanego nauczyciela")} · ${esc(x.replacement_room||"Brak sali")}</div>${x.note?`<div class="muted" style="margin:6px 0 0">${esc(x.note)}</div>`:""}<div class="change-actions"><button class="delete-button" type="button" data-delete="${esc(x.id)}">Usuń zmianę</button></div></article>`).join(""):"<div class=\"empty-admin\">Brak zmian dla wybranego dnia.</div>";document.querySelectorAll("[data-delete]").forEach(b=>b.addEventListener("click",()=>removeChange(b.dataset.delete)));}
async function load(){
  adminChanges=localChanges();
  if(sb){
    const lessons=await sb.from("lesson_plan").select("id,weekday,lesson_number,start_time,end_time,subject,room,teacher").order("weekday").order("lesson_number");
    if(!lessons.error)adminLessons=lessons.data||[];
    const changes=await sb.from("teacher_changes").select("*").order("lesson_date");
    if(!changes.error)adminChanges=changes.data||[];
  }
  $("change-date").value=nextSchoolDay();$("list-date").value=$("change-date").value;fillLessons();renderChanges();
}
async function saveChange(event){event.preventDefault();const option=$("change-lesson").selectedOptions[0];const payload={lesson_plan_id:option.value||null,lesson_number:Number(option.dataset.number),lesson_date:$("change-date").value,change_type:$("change-type").value,replacement_subject:$("change-subject").value.trim(),replacement_teacher:$("change-teacher").value.trim(),replacement_room:$("change-room").value.trim(),teacher_absent:$("change-absent").checked,note:$("change-note").value.trim()};if(!payload.lesson_date||!payload.replacement_subject)return;let saved=false;if(sb&&payload.lesson_plan_id){const result=await sb.from("teacher_changes").upsert(payload,{onConflict:"lesson_plan_id,lesson_date"}).select().single();if(!result.error){const index=adminChanges.findIndex(x=>String(x.lesson_plan_id)===String(payload.lesson_plan_id)&&x.lesson_date===payload.lesson_date);if(index>=0)adminChanges[index]=result.data;else adminChanges.push(result.data);saved=true;}}if(!saved){payload.id=`local-${Date.now()}`;adminChanges=adminChanges.filter(x=>!(x.lesson_number===payload.lesson_number&&x.lesson_date===payload.lesson_date));adminChanges.push(payload);saveLocal();notice("Zapisano lokalnie. Po skonfigurowaniu tabeli teacher_changes zmiana będzie współdzielona.");}else notice("Zmiana została zapisana tylko na wybrany dzień.");$("list-date").value=payload.lesson_date;renderChanges();}
async function removeChange(id){if(!confirm("Usunąć tę zmianę? Stały plan pozostanie bez zmian."))return;const item=adminChanges.find(x=>String(x.id)===String(id));if(item&&!String(id).startsWith("local-")&&sb){const result=await sb.from("teacher_changes").delete().eq("id",id);if(result.error){notice("Nie udało się usunąć zmiany.",true);return;}}adminChanges=adminChanges.filter(x=>String(x.id)!==String(id));saveLocal();renderChanges();notice("Zmiana została usunięta.");}
(async()=>{try{if(!sb)throw new Error("Brak usługi");const {data,error}=await sb.auth.getSession();if(error||!data.session)throw new Error("Brak sesji");$("admin-status").hidden=true;$("admin-app").hidden=false;await load();}catch(error){$("admin-status").innerHTML="Brak dostępu. Zaloguj się kontem administratora, aby otworzyć panel.";}})();
$("change-date").addEventListener("change",fillLessons);$("list-date").addEventListener("change",renderChanges);$("change-form").addEventListener("submit",saveChange);
