-- Uruchom w Supabase SQL Editor. Zmiana dotyczy wyłącznie lesson_date.
create table if not exists public.teacher_changes (
  id bigint generated by default as identity primary key,
  lesson_plan_id bigint references public.lesson_plan(id) on delete cascade,
  lesson_number integer not null,
  lesson_date date not null,
  change_type text not null default 'replacement' check (change_type in ('replacement','block','cancelled')),
  replacement_subject text not null,
  replacement_teacher text not null default '',
  replacement_room text not null default '',
  teacher_absent boolean not null default false,
  note text not null default '',
  created_at timestamptz not null default now(),
  unique (lesson_plan_id, lesson_date)
);
alter table public.teacher_changes add column if not exists lesson_number integer;
alter table public.teacher_changes add column if not exists change_type text not null default 'replacement';
alter table public.teacher_changes add column if not exists replacement_subject text not null default '';
alter table public.teacher_changes add column if not exists replacement_teacher text not null default '';
alter table public.teacher_changes add column if not exists replacement_room text not null default '';
alter table public.teacher_changes add column if not exists note text not null default '';
alter table public.teacher_changes add column if not exists created_at timestamptz not null default now();
create unique index if not exists teacher_changes_lesson_date_unique on public.teacher_changes (lesson_plan_id, lesson_date);
alter table public.teacher_changes enable row level security;
drop policy if exists "teacher changes read for signed users" on public.teacher_changes;
create policy "teacher changes read for signed users" on public.teacher_changes for select to authenticated using (true);
drop policy if exists "teacher changes write for admins" on public.teacher_changes;
create policy "teacher changes write for admins" on public.teacher_changes for all to authenticated using ((auth.jwt()->'app_metadata'->>'role') = 'admin') with check ((auth.jwt()->'app_metadata'->>'role') = 'admin');
