create table if not exists public.remarks (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('remark', 'praise')),
  title text not null check (char_length(title) between 1 and 120),
  content text not null check (char_length(content) between 1 and 500),
  entry_date date not null default current_date,
  created_at timestamptz not null default now()
);

alter table public.remarks enable row level security;

grant select on table public.remarks to anon, authenticated;
grant insert, update, delete on table public.remarks to authenticated;
grant usage, select on sequence public.remarks_id_seq to authenticated;

create policy "remarks are publicly readable"
on public.remarks
for select
to anon, authenticated
using (true);

create policy "authenticated users can create remarks"
on public.remarks
for insert
to authenticated
with check (true);

create policy "authenticated users can update remarks"
on public.remarks
for update
to authenticated
using (true)
with check (true);

create policy "authenticated users can delete remarks"
on public.remarks
for delete
to authenticated
using (true);

create index if not exists remarks_entry_date_idx
on public.remarks (entry_date desc, created_at desc);
